### ISSUE TITLE
Background gradient on game select screen doesn't reach to the top of the window

### ISSUE THREAD

**Issue by BenBergman** [winnitron/WinnitronLauncher#105]
In the game select screen there is a black-transparent gradient over the background. This does not reach to the top of the screen.

![img_20181023_192448](https://user-images.githubusercontent.com/142754/47434009-3c6a4180-d767-11e8-8f4a-fa21c2bc873c.jpg)

**Comment by mrmwiebe** [comment]
I'll make a new branch and try and patch up this resolution stuff.  I need to make it more responsive to fill out the entire screen on larger monitors, cause you can see that the insides of the launcher screen there are at 1080p.  Since we were imagining that this would be running on a dedicated computer, we imagined that you could just set it at 1080p and forget, but will need to eventually make it more responsive.  Will take a look!

**Comment by BenBergman** [comment]
This happens at 1080p too.

**Comment by mrmwiebe** [comment]
Fixed.  Will be available with next release.
