### ISSUE TITLE
Move default playlists directory out of launcher folder structure

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#26]
Related to #25, I'd like to be able to tell people

> nuke c:\winnitron and unzip the new version there. everything will be fine

Without it taking all their installed games with it - especially because that would include local ones not included in a sync.

This is really just a change to the included options json, right?

**Comment by mrmwiebe** [comment]
Yep.  I guess we can include two folders in the zipfile, one for c:\winnitron and one for c:\winnitron_user (with the playlists and attract and music) or something?  then if they want they can just replace the winnitron folder.  I'd like to include the folder with the zip file because then it's a bit easier to set up.  That sound fine?

**Comment by aaronklaassen** [comment]
Yeah doesn't matter to me as long as they're separate.

**Comment by mrmwiebe** [comment]
Realized I fixed this with the last commit as well.  It'll be in the next release.
