### ISSUE TITLE
Plaintext attract screens

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#86]
Imagine a world where I can just drop something like `announcement.txt` into `/Attract` and I get a screen with its contents in attract mode, like we do with images and videos.

**Comment by mrmwiebe** [comment]
Yeah for sure.  It would probably be easiest to have it so that each attract screen is a separate file, but wondering how it might work with any future network support.  So would this be cool?

attract_1.mp4
attract_2.txt
attract_3.png
attract_4.txt
...

Easiest would be Unity just grabbing things by file name, so if you number them then you can control when it goes up, but otherwise it'll just display in the order it picks them up.  Thoughts?

**Comment by aaronklaassen** [comment]
@mrmwiebe  Yeah that's exactly what I was thinking. Just display them in alphabetical order. Network support could be shimmed in much easier once this much is in place.
