### ISSUE TITLE
New menu resolution compatibility

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/WinnitronLauncher#88]
The new UI looks great on a 16:9 display, but is too wide otherwise (these pictures are from a trial run on the Half-a-tron, which is 8:5 / 1440x900).

![img_1934](https://user-images.githubusercontent.com/1580121/36647818-b627e420-1a50-11e8-814f-903a32042085.jpg)
![img_1935](https://user-images.githubusercontent.com/1580121/36647819-b63e0ef8-1a50-11e8-875e-d1da89335d95.jpg)

**Comment by mrmwiebe** [comment]
Hey @aaronklaassen so this is fixed now.  The TopBar (with the winnitron logo) is now responsive, but since the way that I arranged the launcher is very dependant on the global space, I just added a launcher scale option in winnitron_options.json.  Setting that to 0.9 or something should fit it all in.

Let me know if that helps!
